openapi: 3.0.0
info:
  title: API для проекта "Шесть городов".
  description: |-
    *Список ресурсов и маршрутов сервера "Шесть городов".
  version: "1.0.0"
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

tags:
  - name: offers
    description: Действия с объявлениями.
  - name: users
    description: Действия с пользователями.
  - name: comments
    description: Действия с комментариями.

paths:
  /users/register:
    post:
      tags:
        - users
      summary: Регистрация пользователя
      description: Регистрирует нового пользователя
      requestBody:
        description: Информация для создания нового пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createUser'
      responses:
        "201":
          description: Пользователь зарегистрирован. Объект пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "409":
          description: Пользователь с таким email уже существует

  /users/login:
    post:
      tags:
        - users
      summary: Авторизация пользователя
      description: Авторизует пользователя на основе логина и пароля
      requestBody:
        description: Логин и пароль авторизующегося пользователя
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/loginUser'
      responses:
        "200":
          description: Пользователь авторизован. Токен пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/loginResponse'
        "401":
          description: Ошибка авторизации. Неправильный логин или пароль

    get:
      tags:
        - users
      summary: Проверка состояния пользователя
      description: Возвращает информацию по авторизованному пользователю
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Статус авторизации пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/authStatus'
        "401":
          description: Пользователь не авторизован

  /users/logout:
    delete:
      tags:
        - users
      summary: Завершение сессии пользователя.
      description: Разлогинивает пользователя и аннулирует токен.
      security:
        - bearerAuth: []
      responses:
        "204":
          description: Пользователь разлогинен
        "401":
          description: Пользователь не авторизован

  /users/{userId}:
    get:
      tags:
        - users
      summary: Получить данные пользователя по userId
      parameters:
        - name: userId
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Данные пользователя
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        "404":
          description: Пользователь не найден

  /users/{userId}/favorites:
    get:
      tags:
        - users
      summary: Получить список избранных предложений пользователя
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Список избранных предложений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'
        "401":
          description: Пользователь не авторизован

    post:
      tags:
        - users
      summary: Добавить предложение в избранное пользователя
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: string
      requestBody:
        description: ID предложения, добавляемого в избранное
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                offerId:
                  type: string
              required:
                - offerId
      responses:
        "201":
          description: Предложение добавлено в избранное
        "401":
          description: Пользователь не авторизован
        "400":
          description: Некорректные данные

  /users/{userId}/favorites/{offerId}:
    delete:
      tags:
        - users
      summary: Удалить предложение из избранного
      security:
        - bearerAuth: []
      parameters:
        - name: userId
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: string
        - name: offerId
          in: path
          description: Идентификатор предложения
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Предложение удалено из избранного
        "401":
          description: Пользователь не авторизован
        "404":
          description: Предложение не найдено

  /users/{userId}/avatar:
    post:
      tags:
        - users
      summary: Загрузить аватар пользователя
      parameters:
        - name: userId
          in: path
          description: Идентификатор пользователя
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                avatar:
                  type: string
                  format: binary
              required:
                - avatar
      responses:
        "201":
          description: Аватар загружен
          content:
            application/json:
              schema:
                type: object
                properties:
                  filepath:
                    type: string

  /offers:
    get:
      tags:
        - offers
      summary: Получение списка предложений
      description: Возвращает список всех объявлений
      parameters:
        - name: limit
          in: query
          description: Максимальное количество объявлений
          required: false
          schema:
            type: integer
            minimum: 1
      responses:
        "200":
          description: Список объявлений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'

    post:
      tags:
        - offers
      summary: Создание нового предложения
      description: Добавляет новое объявление
      security:
        - bearerAuth: []
      requestBody:
        description: Информация для создания нового объявления
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createOffer'
      responses:
        "201":
          description: Объявление создано
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "401":
          description: Пользователь не авторизован

  /offers/{offerId}:
    get:
      tags:
        - offers
      summary: Получение конкретного предложения
      description: Возвращает данные одного объявления по идентификатору
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Объект объявления
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "404":
          description: Объявление не найдено

    patch:
      tags:
        - offers
      summary: Обновление предложения
      description: Обновляет существующее объявление
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: Данные для обновления объявления
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/updateOffer'
      responses:
        "200":
          description: Объявление обновлено
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/offer'
        "401":
          description: Пользователь не авторизован
        "403":
          description: Доступ запрещен
        "404":
          description: Объявление не найдено

    delete:
      tags:
        - offers
      summary: Удаление предложения
      description: Удаляет объявление по идентификатору
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        "204":
          description: Объявление удалено
        "401":
          description: Пользователь не авторизован
        "403":
          description: Доступ запрещен
        "404":
          description: Объявление не найдено

  /offers/{offerId}/comments:
    get:
      tags:
        - comments
      summary: Получить комментарии для конкретного объявления
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Список комментариев для объявления
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/comment'
        "404":
          description: Объявление не найдено

    post:
      tags:
        - comments
      summary: Добавить комментарий к объявлению
      security:
        - bearerAuth: []
      parameters:
        - name: offerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createComment'
      responses:
        "201":
          description: Комментарий успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
        "401":
          description: Пользователь не авторизован
        "404":
          description: Объявление не найдено

  /offers/bundles/new:
    get:
      tags:
        - offers
      summary: Получить новые предложения
      description: Возвращает список новых объявлений
      responses:
        "200":
          description: Список новых объявлений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'

  /offers/bundles/discussed:
    get:
      tags:
        - offers
      summary: Получить обсуждаемые предложения
      description: Возвращает список самых обсуждаемых объявлений
      responses:
        "200":
          description: Список обсуждаемых объявлений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'

  /offers/premium/{city}:
    get:
      tags:
        - offers
      summary: Получить премиальные предложения по городу
      parameters:
        - name: city
          in: path
          required: true
          schema:
            type: string
            enum:
              - Paris
              - Cologne
              - Brussels
              - Amsterdam
              - Hamburg
              - Dusseldorf
      responses:
        "200":
          description: Список премиальных объявлений
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/offer'
        "400":
          description: Некорректное имя города

  /comments:
    post:
      tags:
        - comments
      summary: Добавить комментарий
      description: Создает комментарий к объявлению
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/createComment'
      responses:
        "201":
          description: Комментарий успешно создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/comment'
        "401":
          description: Пользователь не авторизован
        "404":
          description: Объявление не найдено

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    createUser:
      type: object
      properties:
        email:
          type: string
          format: email
        avatarPath:
          type: string
        firstname:
          type: string
          minLength: 1
          maxLength: 15
        type:
          type: string
          enum: [standard, pro]
        password:
          type: string
          minLength: 6
          maxLength: 12
      required:
        - email
        - firstname
        - type
        - password

    loginUser:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
      required:
        - email
        - password

    user:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        avatarPath:
          type: string
        firstname:
          type: string
        type:
          type: string
          enum: [standard, pro]

    loginResponse:
      type: object
      properties:
        token:
          type: string
        email:
          type: string
          format: email
      required:
        - token
        - email

    authStatus:
      type: object
      properties:
        email:
          type: string
          format: email
      required:
        - email

    createOffer:
      type: object
      properties:
        title:
          type: string
          minLength: 10
          maxLength: 100
        description:
          type: string
          minLength: 20
          maxLength: 1024
        publishDate:
          type: string
          format: date-time
        city:
          type: string
          enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
        adImage:
          type: string
        images:
          type: array
          items:
            type: string
          minItems: 6
          maxItems: 6
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
          minimum: 1
          maximum: 5
        housingType:
          type: string
          enum: [apartment, house, room, hotel]
        rooms:
          type: integer
          minimum: 1
          maximum: 8
        guests:
          type: integer
          minimum: 1
          maximum: 10
        price:
          type: integer
          minimum: 100
          maximum: 100000
        conveniences:
          type: array
          items:
            type: string
            enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]
        commentsCount:
          type: integer
        location:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number
      required:
        - title
        - description
        - publishDate
        - city
        - adImage
        - images
        - isPremium
        - isFavorite
        - rating
        - housingType
        - rooms
        - guests
        - price
        - conveniences
        - commentsCount
        - location

    updateOffer:
      type: object
      properties:
        title:
          type: string
          minLength: 10
          maxLength: 100
        description:
          type: string
          minLength: 20
          maxLength: 1024
        city:
          type: string
          enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
        adImage:
          type: string
        images:
          type: array
          items:
            type: string
          minItems: 6
          maxItems: 6
        isPremium:
          type: boolean
        housingType:
          type: string
          enum: [apartment, house, room, hotel]
        rooms:
          type: integer
          minimum: 1
          maximum: 8
        guests:
          type: integer
          minimum: 1
          maximum: 10
        price:
          type: integer
          minimum: 100
          maximum: 100000
        conveniences:
          type: array
          items:
            type: string
            enum: [Breakfast, Air conditioning, Laptop friendly workspace, Baby seat, Washer, Towels, Fridge]
        location:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number
      required:
        - city
        - adImage
        - isPremium
        - housingType
        - rooms
        - guests
        - price
        - conveniences
        - location

    offer:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        description:
          type: string
        publishDate:
          type: string
          format: date-time
        city:
          type: string
          enum: [Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf]
        adImage:
          type: string
        images:
          type: array
          items:
            type: string
        isPremium:
          type: boolean
        isFavorite:
          type: boolean
        rating:
          type: number
        housingType:
          type: string
        rooms:
          type: integer
        guests:
          type: integer
        price:
          type: integer
        conveniences:
          type: array
          items:
            type: string
        author:
          $ref: '#/components/schemas/user'
        commentsCount:
          type: integer
        location:
          type: object
          properties:
            latitude:
              type: number
            longitude:
              type: number

    createComment:
      type: object
      properties:
        text:
          type: string
          minLength: 5
          maxLength: 1024
        rating:
          type: integer
          minimum: 1
          maximum: 5
        offerId:
          type: string
      required:
        - text
        - rating

    comment:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        publishDate:
          type: string
          format: date-time
        rating:
          type: integer
        user:
          $ref: '#/components/schemas/user'
